### ISSUE TITLE
Implementation of IFRNet

### ISSUE THREAD

**Issue by Tsubajashi** [styler00dollar/VSGAN-tensorrt-docker#10]
Hi!
As always, here may be an interesting AI to play with.
im not sure how much vram it takes, but the speed it cites seems to be pretty good.
Have a look at it.

https://github.com/ltkong218/IFRNet
![vimeo90k](https://user-images.githubusercontent.com/21346945/173323298-a44068e1-b4ad-4a03-95a1-8177170ff03c.png)

**Comment by Tsubajashi** [comment]
oops, seems to be there already. sorry.

**Comment by styler00dollar** [comment]
I added basic IFRNet functionality yeststerday and it will probably be expanded a bit at some point. I need to update the dockers later to include the models.
