### ISSUE TITLE
Google colab request?

### ISSUE THREAD

**Issue by mikebilly** [styler00dollar/VSGAN-tensorrt-docker#12]
I recently stumbled upon this VSGAN-tensorrt-docker and found it so incredible! Could anyone make a google colab notebook that features everything from this VSGAN-tensorrt-docker, so that we could experience the speed of TensorRT! Thanks in advance!

**Comment by styler00dollar** [comment]
There is a colab file in my repository. Are you missing some feature? I guess I could make it more obvious and also link it in the readme.

**Comment by styler00dollar** [comment]
Closing since no reply and a Colab file actually exists.

**Comment by mikebilly** [comment]
Sorry I forgot to check on Github, thanks for the Colab file @styler00dollar! And btw could you add some example blocks of code in that Colab file, such as taking an input.mkv video and interpolate it 4 times using rife, or using realesrgan to upscale an input.png image,... (like example codes for each function of your project). Sorry if this is too much, but I'm pretty new to coding and want to learn more through examples. Really appreciate your work!
