### ISSUE TITLE
Trying On A M1 Mac

### ISSUE THREAD

**Issue by Ghostkwebb** [styler00dollar/VSGAN-tensorrt-docker#14]
So I followed this tutorial https://www.youtube.com/watch?v=B134jvhO8yk&t=0s
But when docker run --privileged --gpus all -it --rm -v /home/vsgan_path/:/workspace/tensorrt styler00dollar/vsgan_tensorrt:latest it just gives me an error that it doesn't find the right amd64 or somthing
and I rage quit deleted it without seeing the full error.
PLS HELP ME :(

**Comment by Ghostkwebb** [comment]
This is the error 
ghostkwebb@Sharads-MacBook-Pro  VSGAN-tensorrt-docker % docker run --privileged --gpus all -it --rm -v //Users/ghostkwebb/Desktop/AI/VSGAN-tensorrt-docker:/workspace/tensorrt styler00dollar/vsgan_tensorrt:latest

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].


pls help me I don't wanna pay money for fricking waifu2x

**Comment by styler00dollar** [comment]
My stuff was not made for arm in mind. And since amd gpus are not supported by docker, I kind of doubt that M1 gpus will work. The only chance you have is to manually compile the ncnn related vapoursynth packages on your system and use it without docker. Vapoursynth should be the most efficient way to use models, many other repos extract into images which is a waste of time and disk io bottleneck for read/write. TensorRT, docker and cuda and so on only works with nvidia.

**Comment by Ghostkwebb** [comment]
Could you tell me how to manually compile? Because there is the software waify2x which uses the stuff u made that's why I wanna know if I can do it too.

**Comment by styler00dollar** [comment]
https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan

**Comment by Ghostkwebb** [comment]
I could install docker just fine but i don't know how to do the other
things that your mentioned

**Comment by styler00dollar** [comment]
The docker was not built for arm, so you can't use the docker and you need to do it manually. Either directly on your system or create a custom arm docker. I do not have an arm system and won't support it. Compile instructions are in the repository, but may differ for arm. 

Docker does only support nvidia gpus though, so installing onto your system is most likely the way.
