### ISSUE TITLE
Support for AITemplate?

### ISSUE THREAD

**Issue by kodxana** [styler00dollar/VSGAN-tensorrt-docker#16]
There is something  that came out recently and it's look promising in terms of performance/speed. Would it be possible  to implement it for ESERGAN mode?
https://github.com/facebookincubator/AITemplate

**Comment by styler00dollar** [comment]
I don't really understand how to use it for now.. It would also only work on specific gpus.

**Comment by kodxana** [comment]
It's similar to Tensor and engine models.

**Comment by styler00dollar** [comment]
It is quite different in terms of code. [It does not seem that easy to add at first glance](https://facebookincubator.github.io/AITemplate/tutorial/how_to_infer_pt.html), doesn't look very complicated, but it will only work on ampere gpus. I have a 1070ti.

**Comment by styler00dollar** [comment]
It seems to be prone to errors and doesn't support certain pytorch operators like PixelShuffle. I couldn't get compact working and that was one of the simplest upscaling networks. I don't think I will add it any time soon.
