### ISSUE TITLE
Crash when using RIFE ensemble models in vsmlrt

### ISSUE THREAD

**Issue by banjaminicc** [styler00dollar/VSGAN-tensorrt-docker#18]
I get this error
```
vapoursynth.Error: operator (): expects 8 input planes
```

from this 
```
import vapoursynth as vs
from vapoursynth import core
core = vs.core
import vsmlrt

clip = core.lsmas.LWLibavSource(source=r"R:\output.mkv",cache=1, prefer_hw=1)
clip = core.resize.Bicubic(clip, matrix_in_s="709", transfer_in_s='709', format=vs.RGBS)
clip = vsmlrt.RIFE(clip, multi=4, model=46, backend=vsmlrt.Backend.TRT(fp16=True), tilesize=[1920,1088])
clip = core.std.AssumeFPS(clip=clip, fpsnum=60, fpsden=1)
clip = core.resize.Bicubic(clip, format=vs.RGB24, matrix_in_s="709")
clip.set_output()
```

**Comment by banjaminicc** [comment]
And if I adapt the rife_trt.py to vsmlrt
I get this
```
vapoursynth.Error: operator (): open engine failed
```

```
import vapoursynth as vs
from vapoursynth import core
core = vs.core
import vsmlrt

clip = core.lsmas.LWLibavSource(source=r"R:\output.mkv",cache=1, prefer_hw=1)
clip = core.resize.Bicubic(clip, matrix_in_s="709", transfer_in_s='709', format=vs.RGBS)
clip = vsmlrt.rife_trt(clip, multi=4, engine_path='R:\rifev4.engine')
clip = core.std.AssumeFPS(clip=clip, fpsnum=60, fpsden=1)
clip = core.resize.Bicubic(clip, format=vs.RGB24, matrix_in_s="709")
clip.set_output()
```

**Comment by banjaminicc** [comment]
```
TensorRT.trtexec [TensorRT v8501] # 
D:\Paths\trtexec.exe --onnx=R:\rife46_ensembleTrue_opset17.onnx 
--timingCacheFile=C:/Users/icckl/AppData/Roaming/VapourSynth/plugins64\models\rife\rife_v4.6.onnx.1088x1920_fp16_workspace512_trt-8501_NVIDIA-GeForce-RTX-3060_3dcbe72f.engine.cache 
--device=0 
--saveEngine=C:/Users//AppData/Roaming/VapourSynth/plugins64\models\rife\rife_v4.6.onnx.1088x1920_fp16_workspace512_trt-8501_NVIDIA-GeForce-RTX-3060_3dcbe72f.engine 
--shapes=input:1x8x1920x1088 --fp16 --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
```
My engine is built with this

**Comment by styler00dollar** [comment]
I tested `trtexec --onnx=rife.onnx --minShapes=input:1x8x64x64 --optShapes=input:1x8x720x1280 --maxShapes=input:1x8x1080x1920 --saveEngine=model.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly` with `rife46_ensembleFalse_opset17.onnx` and `rife46_ensembleTrue_opset17.onnx` and it works fine in my docker. Failure on your end, most likely because you don't use my docker or user error.

**Comment by mafiosnik777** [comment]
> And if I adapt the rife_trt.py to vsmlrt I get this
> 
> ```
> vapoursynth.Error: operator (): open engine failed
> ```
> 
> ```
> import vapoursynth as vs
> from vapoursynth import core
> core = vs.core
> import vsmlrt
> 
> clip = core.lsmas.LWLibavSource(source=r"R:\output.mkv",cache=1, prefer_hw=1)
> clip = core.resize.Bicubic(clip, matrix_in_s="709", transfer_in_s='709', format=vs.RGBS)
> clip = vsmlrt.rife_trt(clip, multi=4, engine_path='R:\rifev4.engine')
> clip = core.std.AssumeFPS(clip=clip, fpsnum=60, fpsden=1)
> clip = core.resize.Bicubic(clip, format=vs.RGB24, matrix_in_s="709")
> clip.set_output()
> ```

You're using vsmlrt's wrapper for RIFE. It doesn't work with sudos rife model.

Use sudos wrapper.
