### ISSUE TITLE
libx265 doesn't support 10bit! Also the commands "bframes=8:psy-rd=1:aq-mode=3" are not working.

### ISSUE THREAD

**Issue by Anon1337Elite** [styler00dollar/VSGAN-tensorrt-docker#23]
Currently libx265 doesn't support 10bit. Also the commands "bframes=8:psy-rd=1:aq-mode=3" are not working which they should with x265.

![219981936-21b8f792-4119-4221-a0a7-a71727990b23](https://user-images.githubusercontent.com/65274305/219983318-aba008b4-49c3-44ec-8465-753c815ab303.png)

**Comment by Anon1337Elite** [comment]
I will try the command, Thanks for testing it. I was trying it earlier and i couldn't get it to work no matter what, spent and hour searching about it, i didn't know it was supposed to be in quotes. 

Edit: I just tried it and it works without quotes, i swear earlier that thing didn't want to work lol. I tried it tons of times console was always showing unrecognized command. Thanks.

**Comment by styler00dollar** [comment]
I recompiled x265 with `-D HIGH_BIT_DEPTH:BOOL=ON` but I don't have time to test now. [Here is the ffmpeg.](https://github.com/styler00dollar/ffmpeg-static-arch-docker/releases/tag/20d-02m-23y) Will test and update docker later.

**Comment by Anon1337Elite** [comment]
> I recompiled x265 with `-D HIGH_BIT_DEPTH:BOOL=ON` but I don't have time to test now. [Here is the ffmpeg.](https://github.com/styler00dollar/ffmpeg-static-arch-docker/releases/tag/20d-02m-23y) Will test and update docker later.

Thanks, will wait for docker update, since i have no idea how to install that lol. 

I found where the file is but dont have write access for it, i give up lol, after distro no write access, no idea how to access it.

\\wsl.localhost\docker-desktop-data\mnt\wslg\distro\data\docker\overlay2\XXXXX\diff\usr\local\bin\ffmpeg

**Comment by Anon1337Elite** [comment]
I figured it out and can confirm it is working perfectly thank you.
