### ISSUE TITLE
Is there anything i should be using for Anime upscale from "SIMILARITY" & "SCENE DETECT" ? (Question/Help)

### ISSUE THREAD

**Issue by Anon1337Elite** [styler00dollar/VSGAN-tensorrt-docker#24]
Sorry if this are some shit questions, i am just trying to understand if anything would help me with this and possibly speed up the process. Thank you.

I am not familiar on how these work. Should i at least be using the one with no AI Detection ?

clip = core.misc.SCDetect(clip=clip, threshold=0.100)

Also anything to use from here that would help with anime ?

    ###############################################
    # SIMILARITY
    # Set properties in clip for it to be applied
    # SSIM for deduplication in frame interpolation

    # offs1 = core.std.BlankClip(clip, length=1) + clip[:-1]
    # offs1 = core.std.CopyFrameProps(offs1, clip)
    # 0 = PSNR, 1 = PSNR-HVS, 2 = SSIM, 3 = MS-SSIM, 4 = CIEDE2000
    # clip = core.vmaf.Metric(clip, offs1, 2)

**Comment by styler00dollar** [comment]
There are 2 kinds of dedup, vfi dedup/sc and upscale dedup. I guess I could write it more clearly in the readme, but everything is in the config file. https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/1254e8e51233f9e849d879f897f726464d6dd13a/inference_config.py#L92-L97

**Comment by Anon1337Elite** [comment]
> There are 2 kinds of dedup, vfi dedup/sc and upscale dedup. I guess I could write it more clearly in the readme, but everything is in the config file.
> 
> https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/1254e8e51233f9e849d879f897f726464d6dd13a/inference_config.py#L92-L97

In your opinion is it worth using, is the speed gain large or is it something that might mess up and take frames as dupes when they arent ?

**Comment by styler00dollar** [comment]
It depends on your content of course. Average speedup was around 30% on animated content.
