### ISSUE TITLE
Converting Compact to Onnx, Size Mismatch/Torch.Size, How can i setup the correct parameters in the py file, FP16/32 Question  [Help/Question]

### ISSUE THREAD

**Issue by Anon1337Elite** [styler00dollar/VSGAN-tensorrt-docker#25]
I am running into this error when converting, i know i need to set the correct parameters of the model in the convert_compact_to_onyx.py. But i don't know how, How do i see the current model parameters and what exactly should i change or add in the convert_compact_to_onyx.py. Thank you.

Conversion error:
```
RuntimeError: Error(s) in loading state_dict for SRVGGNetCompact:
        size mismatch for body.34.weight: copying a param with shape torch.Size([3, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 64, 3, 3]).
        size mismatch for body.34.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([48]).
```

**Also wanted to ask for FP16 do i change from RGBS to RGBH over here, also do i need to change this when creating the .engine file or when up-scaling a video ?:**

`  clip = vs.core.resize.Bicubic(clip, format=vs.RGBS, matrix_in_s="709")`

To 

`  clip = vs.core.resize.Bicubic(clip, format=vs.RGBH, matrix_in_s="709")`

The command is always the same for FP16 and FP32 correct ?

`trtexec --fp16 --onnx=model_fp16.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=model.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly`

**Comment by styler00dollar** [comment]
Why do you keep mixing github issues.
1. For official models you can look in official code. For fanmade models you simply need to know what they did.
2. Fp16 onnx to engine will require fp16 (rgbh) input, while fp32 onnx will require fp32 (rbgs) input. You can build both with fp16, but the difference will be amount of transferred data. It is recommended to use fp16 onnx if fp16 is used to use rgbh.
