### ISSUE TITLE
Steps PLEASE

### ISSUE THREAD

**Issue by adhityanadooli** [styler00dollar/VSGAN-tensorrt-docker#26]
Please help me out ima noob and this is confusing, i don't know what im doing. Discord is light!#7926

**Comment by styler00dollar** [comment]
Read the readme and look into `inference_config.py`.

**Comment by adhityanadooli** [comment]
i did but i got an error when doing the download from scratch

**Comment by styler00dollar** [comment]
What? Be more specific. And I am not techsupport in github issues. Following the readme should be enough. If there is nothing specific to solve I will just close the issue.

**Comment by adhityanadooli** [comment]
For this step: # Build docker manually
# This step is not needed if you already downloaded the docker and is only needed if yo
# want to build it from scratch. Keep in mind that you need to set env variables in windows differently and
# this command will only work in linux. Run that inside that directory
DOCKER_BUILDKIT=1 docker build -t styler00dollar/vsgan_tensorrt:latest .
# If you want to rebuild from scratch or have errors, try to build without cache
DOCKER_BUILDKIT=1 docker build --no-cache -t styler00dollar/vsgan_tensorrt:latest . 

When i ran it it said a fatal error has occurred and something about cc1plus, error code 2 and error code 1. I tried both builders .

**Comment by styler00dollar** [comment]
Please use proper formatting, this is painful to look at. And secondly, I wrote:
```
# Download prebuild image from dockerhub (recommended)
docker pull styler00dollar/vsgan_tensorrt:latest
```
in the readme. Just use 
```
docker-compose run --rm vsgan_tensorrt
```
