### ISSUE TITLE
Unable to get and run docker image

### ISSUE THREAD

**Issue by lurkydismal** [styler00dollar/VSGAN-tensorrt-docker#29]
```
$ sudo aptitude install docker nvidia-docker nvidia-container-toolkit docker-compose docker-buildx
```

Added my user to kvm group et la.

```
$ newgrp docker
$ docker pull styler00dollar/vsgan_tensorrt:latest
```

```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
```

```
$ git clone https://github.com/NotGlop/docker-drag
$ cd docker-drag
$ python docker_pull.py styler00dollar/vsgan_tensorrt:latest
```

Took so long and after ~10 hours of waiting with net speed around 100mb / sec on download/ upload,
so i decided to cancel it. The last file that even havent finished pulling was `5537e544ef988f4cd82c06b8d0c919448d2f76ac33509a9b5fb5979b73216c58.json`

**Comment by styler00dollar** [comment]
This repository contains yaml files and you did not run the compose command within the vsgan folder. 

`docker-drag` is not supposed to take that long, but generates a ~30-50gb tar file if I remember correctly. Make sure you have space.

**Comment by lurkydismal** [comment]
I have around 7 TB of free ext4 space and have tried on 200 GB zfs.

I need to clone this repo and run compose or somehow get to the pulled one ?

**Comment by styler00dollar** [comment]
Clone repo and run `docker-compose run --rm vsgan_tensorrt` within it.

**Comment by lurkydismal** [comment]
Why not to write `Clone repo` as mandatory step, bc it does look like i can freely skip it ?

**Comment by styler00dollar** [comment]
Please read more carefully, I did write:
```
# run the docker with docker-compose 
# go into the vsgan folder, inside that folder should be compose.yaml
```

**Comment by lurkydismal** [comment]
And when i saw this i got thought that i need to find where it got pulled.
