### ISSUE TITLE
core.num.thread ram usage influence

### ISSUE THREAD

**Issue by adhityanadooli** [styler00dollar/VSGAN-tensorrt-docker#33]
How should i change the this number to stop my out of memory errors? 
![image](https://user-images.githubusercontent.com/127269031/226506234-743d8dc2-c1f1-42c7-a640-041aa4324927.png)

**Comment by mafiosnik777** [comment]
That only influences system memory, not video memory.

We can't help you how to fix your out of memory errors without any info on what you're trying to run.

**Comment by adhityanadooli** [comment]
Cant even open the project currently but I was running CUGAN on a mp4 with this command: ffmpeg -f vapoursynth -i inference.py example.mp4 -y.

**Comment by styler00dollar** [comment]
Optimal settings depends on your system. That is to configure vapoursynth concurrency and occupies ram.
