### ISSUE TITLE
Docker desktop wont run the container

### ISSUE THREAD

**Issue by adhityanadooli** [styler00dollar/VSGAN-tensorrt-docker#34]
Docker wont run the container and everytime it tries it stalls, i have tried reinstaling the image and reinstalling destop docker but it wont work. Even tried running docker run --privileged --gpus all -it --rm -v /mnt/c/VSGAN/VSGAN-tensorrt-docker:/workspace/tensorrt styler00dollar/vsgan_tensorrt:latest     but that didnt work either. EX: (its stuck there)
![image](https://user-images.githubusercontent.com/127269031/227050098-cfeb472d-7867-48c4-8a80-45a25a2ef7fe.png)

**Comment by styler00dollar** [comment]
Don't think I ever saw this before.

**Comment by adhityanadooli** [comment]
Diagonsed with docker destop: 
![image](https://user-images.githubusercontent.com/127269031/227736095-48ed5833-bf29-484b-96c6-7f678618b995.png)

**Comment by HtronFerns** [comment]
@lightyfr How did you manage to fix it? I am encountering the same error...

**Comment by adhityanadooli** [comment]
@HtronFerns 
![image](https://user-images.githubusercontent.com/127269031/227810068-f97b2d55-9353-4b90-a29b-95cc5ebd904d.png)
****
https://github.com/microsoft/WSL/issues/5092#issuecomment-743937383

Didn't do myself but this should work.

**Comment by HtronFerns** [comment]
@lightyfr 
I managed to clear the errors/repair the wls2 drive going by what you sent.

We had the same self diagnose before the fix, but after it, it seems its already fixed.

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
0 failures detected
self-diagnose took 9.2756304s

However, I still cannot run the container after being created from the "docker-compose run --rm vsgan_tensorrt" 
If I try to run it within the docker GUI, its keeps displaying Cannot start Docker Compose application. Reason: exit status 1

**Comment by adhityanadooli** [comment]
@HtronFerns I am not the typa guy that can answer this question, reach out to @styler00dollar and mafiosnik, you can also join their discord server: https://discord.gg/enhance-everything-547949405949657098. there is a vsgan thread there check it out. There they can assist you better.

**Comment by HtronFerns** [comment]
@lightyfr 
Thanks for the heads up!
On a side note, did you really manage to run the container after your said fix?
Just wanna know what happened on your end..

**Comment by styler00dollar** [comment]
According to a person contacting me, updating desktop docker to the latest version seems to fix this issue of "waiting and nothing happening". Apparently old versions of docker contribute to this. `4.16.3` works on his Windows 11, but I am not sure if this is the exact same issue.

**Comment by styler00dollar** [comment]
After more testing and more people debugging, I can confirm that **`4.17.1` is broken, do not use it. `4.16.3`  and `4.17.0` works on my Windows 10.**
