### ISSUE TITLE
How to convert my trained rife pytorch model to ncnn model?

### ISSUE THREAD

**Issue by JiadiLee** [styler00dollar/VSGAN-tensorrt-docker#37]
The author of ncnn provides a method for converting pytorch model to ncnn model from pnnx. But I encountered some issues during the conversion process. So, I would like to inquire about it, how didyou perform model transformation? Is there many modifications to the original model during the conversion process?

**Comment by styler00dollar** [comment]
What model do you refer to? `pnnx` was usually broken for me, I converted with onnx. How hard it is to export and if workarounds are needed depends on model architecture.

**Comment by JiadiLee** [comment]
> What model do you refer to? `pnnx` was usually broken for me, I converted with onnx. How hard it is to export and if workarounds are needed depends on model architecture

Thank you for your reply! 
I used **rife_v4.6** for model conversion, but I have a little change for adapting to my scene. I will attempt to converted with onnx and hope to succeed！

**Comment by styler00dollar** [comment]
Converting rife is quite hard and involves a lot of workarounds. I could elaborate later if you want, but it involves changing python code, having specific pytorch version, simplifying the onnx and manually editing param file.

**Comment by JiadiLee** [comment]
> Converting rife is quite hard and involves a lot of workarounds. I could elaborate later if you want, but it involves changing python code, having specific pytorch version, simplifying the onnx and manually editing param file.

This conversion sounds very complex, but I need rife to run quickly on the mobile end for my test. I did encounter many problems using pnnx conversion directly. If you can elaborate the method of conversion with onnx, it will be of great help to me.
Very thank you for your reply！

**Comment by styler00dollar** [comment]
Get this pytorch version (other versions can result in errors):
```
pip install torch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 --extra-index-url https://download.pytorch.org/whl/cu113
```
In the rife architecture, `timestep` needs to be created like this:
```
timestep = (x[:, :1].clone() * 0 + 1) * timestep
timestep = timestep.float() # or .half(), it is **very** important to use .float() OR .half()
```
Replace warp in the architecture with another operator. I use `pow`. It's only important to use something that rife doesn't already use and something that `ncnn` supports. `ncnn` does not support `warp` and I use `pow` to replace it later with nihuis `warp` plugin. I use `pow`, but since `pow` does not allow different tensors, we crop this tensor differently. This needs to be fixed later. This needs to be done to get onnx.
```
warped_img0 = warp(img0, flow[:, :2])
warped_img1 = warp(img1, flow[:, 2:4])

to 

warped_img0 = img0**flow[:,:3]
warped_img1 = img1**flow[:,1:4]
```
If you encounter other errors, I think you can solve them, shouldn't be hard. The hardest part is to fix `timestep` and `warp`.

Export onnx like this (too high opset will error):
```
test_input = torch.rand(1, 3, 256, 256).cuda()
timestep = torch.Tensor([0.5]).cuda()

torch.onnx.export(
    model,
    (test_input, test_input, torch.Tensor([0.5]).cuda()),
    "rife.onnx",
    verbose=False,
    opset_version=11,
    input_names=["in0", "in1", "in2"],
    output_names=["out0"],
)
```
Use `https://convertmodel.com/` onnx -> onnx and simplify/optimize. Use the same website to use this optimized onnx and convert onnx -> bin/param.

Open param file and look at any mentions of `pow`.  Replace `pow` with `warp`.

```
BinaryOp                 pow_3                   2 1 in0_splitncnn_3 210 211 0=6

to 

rife.Warp                 warp_3                   2 1 in0_splitncnn_3 210 211 0=6
```
Then fix the cropping. Layers with crop are nearby these `rife.Warp` and just change back to 2 dimensions. Make sure you crop correctly with 2 dimensions. For example:
```
# 1,0 / 1,2 = [:, :2]
Crop                     Slice_166                1 1 300_splitncnn_3 306 -23309=1,0 -23310=1,2 -23311=1,0
rife.Warp                 warp_167                  2 1 in0_splitncnn_2 306 307 0=6
# 1,2 / 1,4 = [:, 2:4]
Crop                     Slice_172                1 1 300_splitncnn_2 312 -23309=1,2 -23310=1,4 -23311=1,0
rife.Warp                 warp_173                  2 1 in1_splitncnn_2 312 313 0=6
```
With this information you should be also able to do it. If you use ensemble, you can export it with the same concept, but you need to fix tensor shapes and fix cropping in param file. You can find all my models [here](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/tree/master/models).

**Comment by styler00dollar** [comment]
Closing issue since I think I solved it.

**Comment by JiadiLee** [comment]
Very thank you for your reply! It's helpful for me! I think it can solve my problem!

**Comment by JiadiLee** [comment]
> Closing issue since I think I solved it.

I try this convert method to v4.6 and get bin and param file. But I use it to inference in ncnn failed! I received an error message. So I try your v4.6 model and received the same error. Then, I try the v4.6 model maded by nihui didn't receive this error. I'm not sure where the problem is.

**error message:**
physical count=[0], gpu info index=[0], gpu device name=[NVIDIA GeForce RTX 3080 Ti]
[0 NVIDIA GeForce RTX 3080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3080 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3080 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3080 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
**layer MemoryData not exists or registered**

**Comment by styler00dollar** [comment]
Well it tells you that you did not compile ncnn with `MemoryData`. Recompile your ncnn with this. You can toggle with what features you want to compile ncnn. `MemoryData` is required for 4.6.

**Comment by JiadiLee** [comment]
> Well it tells you that you did not compile ncnn with `MemoryData`. Recompile your ncnn with this. You can toggle with what features you want to compile ncnn. `MemoryData` is required for 4.6.

It is indeed this problem! I didn't recompile ncnn with layer_memorydata! Thank you very much for your help!

**Comment by JiadiLee** [comment]
> Well it tells you that you did not compile ncnn with `MemoryData`. Recompile your ncnn with this. You can toggle with what features you want to compile ncnn. `MemoryData` is required for 4.6.

But I have encountered a new problem. I want to use "dynamic_axes" to get a dynamic input support. But I convert model from "https://convertmodel.com/" to ncnn model. I can't get dynamic model. I only input static shape can get Correct output. My ecport code is as follow:

```
test_input = torch.rand(1, 3, 256, 256).cuda()
timestep = torch.Tensor([0.5]).cuda()
dynamic_axes = {
    "in0": {0: "batch_size", 2: "width", 3: "height"},
    "in1": {0: "batch_size", 2: "width", 3: "height"},
    "out0": {0: "batch_size", 2: "width", 3: "height"},
}

torch.onnx.export(
    flownet,
    (test_input, test_input, timestep),
    "rife.onnx",
    verbose=False,
    opset_version=11,
    input_names=["in0", "in1", "in2"],
    output_names=["out0"],
    dynamic_axes=dynamic_axes,
    )
```

**Comment by styler00dollar** [comment]
In my example I did show that I exported without dynamic. Ncnn model will still accept different shapes despite this. You just need to make sure the data is padded to valid resolutions when you use the model or do it like me and pad/crop within the model.

**Comment by JiadiLee** [comment]
> In my example I did show that I exported without dynamic. Ncnn model will still accept different shapes despite this. You just need to make sure the data is padded to valid resolutions when you use the model or do it like me and pad/crop within the model.

Thank you very much!

**Comment by Siziff** [comment]
@styler00dollar  I follow all the instructions, but I get an error. How did you fix this error?
```
TypeError: upsample_bilinear2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, list), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, list)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)
```
