### ISSUE TITLE
No module named 'vsbasicvsrpp'

### ISSUE THREAD

**Issue by xt851231** [styler00dollar/VSGAN-tensorrt-docker#4]
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "inference.py", line 12, in <module>
    from vsbasicvsrpp import BasicVSRPP
ModuleNotFoundError: No module named 'vsbasicvsrpp'

**Comment by styler00dollar** [comment]
I think I heard of that error from another person as well. I need to look into it.

**Comment by mmkzer0** [comment]
I am experiencing the exact same problem. When I try to run inference.py, the program exits with 

> Python exception: No module named ‚vsbasicvsrpp‘.

Edit: I resolved the issue. The modules „vsbasicvsrpp“ and „scipy“ were missing. I installed them via 

> pip install vsbasicvsrpp scipy

and was able to run VSGAN without any issues after.

**Comment by styler00dollar** [comment]
Seems like I accidentally deleted it when I was refactoring the dockerfile. I added it back. Manually building the docker with the dockerfile should work fine now, but due to bad internet I can only update dockerhub later.

**Comment by styler00dollar** [comment]
Should be fixed now.
