### ISSUE TITLE
Files with " - " in the name cause crash.

### ISSUE THREAD

**Issue by darkcristle** [styler00dollar/VSGAN-tensorrt-docker#40]
Basically the title.   It took me a while to figure out what exactly was causing my crashes.   Attempting to run "main.py" caused the encoder to exit.   After some reading of the ffmpeg docs it seems that the " -  " (including spaces) is used to mark a pipe.  As my usual episode naming scheme is "EPISODENUMBER - RESOLUTION.EXTENSION" this was problematic. I was unable to get any file with that sequence of characters to process correctly.    Removing the spaces with PowerRename seemed to correct the issue.

I doubt this is something that is fixable on your end.   Just posting this here for any future people having this issue.   I am currently unaware of any other illegal characters.

The exact error was:

`Unable to choose an output format for 'workspace/tensorrt/output/S01E01'; use a standard extension for the filename or specify the format manually`

I did attempt to specify the format manually with the `-f matroska` flag before the output.   Unfortunately, it seems that due to ffmpeg reading the " - " as a new pipe input it is not actually possible to key the flag to the output wanted.

**Comment by styler00dollar** [comment]
Grab the newest `main.py` where filenames are wrapped with an apostroph to allow special characters. https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/f018734fefb18a98005c4609216dee2dc417438e/main.py#L74 With that, `test - test.mkv`  works fine. Without that, it will not work with characters like space.

**Comment by styler00dollar** [comment]
I guess I can mark this as solved, since there are no further questions.
