### ISSUE TITLE
Environmental Variable "NVIDIA_DRIVER_CAPABILITIES=all" needs to be set in compose file for h265 NVENC

### ISSUE THREAD

**Issue by darkcristle** [styler00dollar/VSGAN-tensorrt-docker#42]
Attempting to use a custom ffmpeg command to render using hevc_nvenc caused the following error:

`
[hevc_nvenc @ 0x55ca461fa380] Cannot load libnvidia-encode.so.1  
[hevc_nvenc @ 0x55ca461fa380] The minimum required Nvidia driver for nvenc is (unknown) or newer    `

[This](https://stackoverflow.com/questions/52062888/running-ffmpeg-with-nvenc-inside-nvidia-docker) post suggested setting an environmental variable to pass through additional driver functions.   It seems to have worked.

**Comment by styler00dollar** [comment]
I can replicate the issue. I had this variable in one docker step prior, but not in the final step when I did big changes to the docker. `NVIDIA_DRIVER_CAPABILITIES=all python main.py` or `export NVIDIA_DRIVER_CAPABILITIES=all` does not seem to fix it. It probably needs to be applied in the dockerfile in the final step.

**Comment by styler00dollar** [comment]
Fixed.
