### ISSUE TITLE
Potential Addition of RSTT

### ISSUE THREAD

**Issue by Tsubajashi** [styler00dollar/VSGAN-tensorrt-docker#6]
https://github.com/llmpass/RSTT

seems like its pretty fast and a good combination of interpolation and upscaling at the same time.

i wasnt able to verify its speed, nor its quality, but it does sound rather promising, given that it has upscaling and interpolation at the same time in one model.

Paper are here: https://arxiv.org/abs/2203.14186

**Comment by styler00dollar** [comment]
I quickly tested it and the best input resolution I could get with 8gb vram is [1,4,3,56,56]. :( A 56px image sequence is way too small, won't add. I hope people will improve transformers.

**Comment by Tsubajashi** [comment]
Sad, had good hopes with the results on the repo.

I'll still keep a lookout so this repo can get many additions
