### ISSUE TITLE
Is it possible to use nvenc_h264?

### ISSUE THREAD

**Issue by ghost** [styler00dollar/VSGAN-tensorrt-docker#62]
Hi instead of using default main.py implementation is it possible to use nvenc_h264? also is there any difference between `-crf 10 -preset slow` and `-crf 10`  except size?

**Comment by styler00dollar** [comment]
You can adjust the ffmpeg commands yourself and view functionality with `ffmpeg -encoders` and `ffmpeg -decoders`.
```
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
```
A preset is a collection of options that will provide a certain encoding speed to compression ratio. [source](https://trac.ffmpeg.org/wiki/Encode/H.264)
