### ISSUE TITLE
Module not found 'scipy'

### ISSUE THREAD

**Issue by terminatedkhla** [styler00dollar/VSGAN-tensorrt-docker#7]
I can't run my inference.py without getting this error message. Can someone direct me to where I can get the repo?

 File "/usr/local/lib/python3.8/dist-packages/mmedit/core/evaluation/metrics.py", line 7, in <module>
    from scipy.ndimage import convolve
ModuleNotFoundError: No module named 'scipy'

pipe:: Invalid data found when processing input

**Comment by terminatedkhla** [comment]
![image](https://user-images.githubusercontent.com/105093061/167236131-9481f453-2cd8-4a23-83f6-65d88298b5af.png)

**Comment by styler00dollar** [comment]
Interesting. Could you also post the error lines prior, so I could see which line caused this? As a quick fix you can just run 'pip install scipy'.

**Comment by terminatedkhla** [comment]
I don't have access to the other error messages, but the pip install worked for that issue. 
The error came up after I ran this sequence before:

docker run --privileged --gpus all -it --rm -v //c/Users/efmcp/Documents/VSGAN/VSGAN-tensorrt-docker-main:/workspace/tensorrt vsgan_tensorrt:latest

cd tensorrt

vspipe -c y4m inference.py - | ffmpeg -i pipe: -c:v ffv1 -level 3 -threads 16 -slices 16 output.mk

This is the modified inference
`import sys
sys.path.append('/workspace/tensorrt/')
import vapoursynth as vs
from src.esrgan import ESRGAN_inference # esrgan and realesrgan
from src.SRVGGNetCompact import SRVGGNetCompactRealESRGAN # realesrgan anime video
from src.vfi_model import video_model # any vfi model, in this case rvp1 as demonstration
from src.sepconv_enhanced import sepconv_model # uses cupy, no tensorrt
from src.rife import RIFE # tensorrt not possible
from vsswinir import SwinIR # https://github.com/HolyWu/vs-swinir # currently not tensorrt, didn't try
from src.egvsr import egvsr_model # currently not tensorrt
from src.cugan import cugan_inference
from vsbasicvsrpp import BasicVSRPP
from src.realbasicvsr import realbasicvsr_model
from src.film import FILM_inference
from src.pan import PAN_inference

core = vs.core
vs_api_below4 = vs.__api_version__.api_major < 4
core = vs.core
core.num_threads = 4 # can influence ram usage
# only needed if you are inside docker
core.std.LoadPlugin(path='/usr/lib/x86_64-linux-gnu/libffms2.so')
core.std.LoadPlugin(path='/usr/local/lib/libvstrt.so')

video_path = "testvideo.mkv"
# cfr video
clip = core.ffms2.Source(source=video_path)
# vfr video (untested)
#clip = core.ffms2.Source(source='input.mkv', fpsnum = 24000, fpsden = 1001)

# resizing with descale
# Debilinear, Debicubic, Delanczos, Despline16, Despline36, Despline64, Descale
#clip = core.descale.Debilinear(clip, 1280, 720)

###############################################
# COLORSPACE
###############################################
# convert colorspace
clip = vs.core.resize.Bicubic(clip, format=vs.RGBS, matrix_in_s='709')
# convert colorspace + resizing
#clip = vs.core.resize.Bicubic(clip, width=848, height=480, format=vs.RGBS, matrix_in_s='709')

###############################################

# these demos work out of the box because docker also downloads the needed models, if you want other models, just add them
# you can combine everything however you want

###############################################
# MODELS (CUDA)
###############################################
# sepconv
#clip = sepconv_model(clip)
# RIFE4
# rife4 can do cuda and ncnn, but only cuda is supported in docker
# models: rife40 | rife41 | sudo_rife4
# clip = RIFE(clip, multi = 2, scale = 1.0, fp16 = False, fastmode = False, ensemble = True, model_version = "sudo_rife4", psnr_dedup = False, psnr_value = 70, ssim_dedup = False, ms_ssim_dedup = False, ssim_value = 0.999, backend_inference = "cuda")
# VFI example for jit models
#clip = video_model(clip, fp16=False, model_path="/workspace/rvpV1_105661_G.pt")
# SwinIR
#clip = SwinIR(clip, task="lightweight_sr", scale=2)
# ESRGAN / RealESRGAN
# tta_mode 1-7, means the amount of times the image gets processed while being mirrored
#clip = ESRGAN_inference(clip=clip, model_path="/workspace/4x_fatal_Anime_500000_G.pth", tile_x=400, tile_y=400, tile_pad=10, fp16=False, tta=False, tta_mode=1)
#clip = ESRGAN_inference(clip=clip, model_path="/workspace/RealESRGAN_x4plus_anime_6B.pth", tile_x=480, tile_y=480, tile_pad=16, fp16=False, tta=False, tta_mode=1)
# RealESRGAN Anime Video example
# backends: tensorrt, cuda, onnx, quantized_onnx
#clip = SRVGGNetCompactRealESRGAN(clip, scale=2, fp16=True, backend_inference = "tensorrt")
# EGVSR
#clip = egvsr_model(clip, interval=15)
# BasicVSR++
# 0 = REDS, 1 = Vimeo-90K (BI), 2 = Vimeo-90K (BD), 3 = NTIRE 2021 - Track 1, 4 = NTIRE 2021 - Track 2, 5 = NTIRE 2021 - Track 3
#clip = BasicVSRPP(clip, model = 1, interval = 30, tile_x = 0, tile_y = 0, tile_pad = 16, device_type = 'cuda', device_index = 0, fp16 = False, cpu_cache = False)
# RealBasicVSR
#clip = realbasicvsr_model(clip, interval=15, fp16=True)
# cugan
# scales: 2 | 3 | 4, kind_model: no_denoise | denoise3x | conservative, backend_inference: cuda | onnx
# only cuda supports tiling
clip = cugan_inference(clip, fp16 = True, scale = 2, kind_model = "conservative", backend_inference = "cuda", tile_x=512, tile_y=512, tile_pad=10, pre_pad=0)
# FILM
# models: l1 | vgg | style
#clip = FILM_inference(clip, model_choise = "vgg")
# vs-mlrt (you need to create the engine yourself)
#clip = core.trt.Model(clip, engine_path="/workspace/tensorrt/real2x.engine", tilesize=[854, 480], num_streams=6)
# vs-mlrt (DPIR)
# DPIR does need an extra channel
#sigma = 10.0
#noise_level_map = core.std.BlankClip(clip, width=1280, height=720, format=vs.GRAYS)
#clip = core.trt.Model([clip, core.std.BlankClip(noise_level_map, color=sigma/255.0)], engine_path="model.engine", tilesize=[1280, 720], num_streams=2)
# PAN
# scale = 2 | 3 | 4
#clip = PAN_inference(clip, scale=2, fp16=True)

###############################################
# [NOT IN DOCKER] MODELS (NCNN)
# Only recommended for AMD GPUS, further instructions in README
###############################################
#from src.SRVGGNetCompact_ncnn import SRVGGNetCompactRealESRGAN_ncnn

# Rife ncnn
#clip = RIFE(clip, multi = 2, scale = 1.0, fp16 = True, fastmode = False, ensemble = True, psnr_dedup = False, psnr_value = 70, ssim_dedup = True, ms_ssim_dedup = False, 
#             ssim_value = 0.999, backend_inference = "ncnn")
# RealESRGAN example
#clip = SRVGGNetCompactRealESRGAN(clip, scale=2, fp16=True, backend_inference = "ncnn", param_path = "test.param", bin_path = "test.bin")
# Waifu2x
# 0 = upconv_7_anime_style_art_rgb, 1 = upconv_7_photo, 2 = cunet (For 2D artwork. Slow, but better quality.)
#clip = core.w2xnvk.Waifu2x(clip, noise=0, scale=2, model=0, tile_size=0, gpu_id=0, gpu_thread=0, precision=16)

###############################################
# Deduplicated inference for faster inference
# only use this for upscaling
###############################################
#from src.dedup import return_frames
#frames_duplicated, frames_duplicating = return_frames(video_path, psnr_value=50)
#clip = core.std.DeleteFrames(clip, frames_duplicated)
# do upscaling here
#clip = core.std.DuplicateFrames(clip, frames_duplicating)
###############################################
# Inference with scene detection
# only use this for frame interpolation
###############################################
#from src.scene_detect import find_scenes
#skip_framelist = find_scenes(video_path, threshold=30)
#clip = RIFE(clip, multi = 2, scale = 1.0, fp16 = True, fastmode = False, ensemble = True, psnr_dedup = False, psnr_value = 70, ssim_dedup = True, ms_ssim_dedup = False, ssim_value = 0.999, skip_framelist=skip_framelist)
###############################################
# OUTPUT
###############################################
clip = vs.core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s="709")
clip.set_output()
`

**Comment by terminatedkhla** [comment]
Here are the prior lines:

Microsoft Windows [Version 10.0.22598.200]
(c) Microsoft Corporation. All rights reserved.

C:\Users\efmcp>docker run --privileged --gpus all -it --rm -v //c/Users/efmcp/Documents/VSGAN/VSGAN-tensorrt-docker-main:/workspace/tensorrt vsgan_tensorrt:latest

=====================
== NVIDIA TensorRT ==
=====================`

NVIDIA Release 21.12 (build 29870938)
NVIDIA TensorRT Version 8.2.1
Copyright (c) 2016-2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Container image Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

https://developer.nvidia.com/tensorrt

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

To install Python sample dependencies, run /opt/tensorrt/python/python_setup.sh

To install the open-source samples corresponding to this TensorRT release version
run /opt/tensorrt/install_opensource.sh.  To build the open source parsers,
plugins, and samples for current top-of-tree on master or a different branch,
run /opt/tensorrt/install_opensource.sh -b <branch>
See https://github.com/NVIDIA/TensorRT for more information.

root@5c2d1ace25dd:/workspace# cd tensorrt
root@5c2d1ace25dd:/workspace/tensorrt# vspipe -c y4m inference.py - | ffmpeg -i pipe: -c:v ffv1 -level 3 -threads 16 -slices 16 output.mkv
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Information: Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
Information: Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
Script evaluation failed:
Python exception: No module named 'scipy'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2886, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2887, in vapoursynth._vpy_evaluate
  File "inference.py", line 13, in <module>
    from src.realbasicvsr import realbasicvsr_model
  File "/workspace/tensorrt/src/realbasicvsr.py", line 3, in <module>
    from mmedit.models.registry import BACKBONES, COMPONENTS, LOSSES, MODELS
  File "/usr/local/lib/python3.8/dist-packages/mmedit/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401, F403
  File "/usr/local/lib/python3.8/dist-packages/mmedit/models/backbones/__init__.py", line 14, in <module>
    from .sr_backbones import (EDSR, LIIFEDSR, LIIFRDN, RDN, SRCNN, BasicVSRNet,
  File "/usr/local/lib/python3.8/dist-packages/mmedit/models/backbones/sr_backbones/__init__.py", line 9, in <module>
    from .liif_net import LIIFEDSR, LIIFRDN
  File "/usr/local/lib/python3.8/dist-packages/mmedit/models/backbones/sr_backbones/liif_net.py", line 6, in <module>
    from mmedit.datasets.pipelines.utils import make_coord
  File "/usr/local/lib/python3.8/dist-packages/mmedit/datasets/__init__.py", line 2, in <module>
    from .base_dataset import BaseDataset
  File "/usr/local/lib/python3.8/dist-packages/mmedit/datasets/base_dataset.py", line 7, in <module>
    from .pipelines import Compose
  File "/usr/local/lib/python3.8/dist-packages/mmedit/datasets/pipelines/__init__.py", line 16, in <module>
    from .loading import (GetSpatialDiscountMask, LoadImageFromFile,
  File "/usr/local/lib/python3.8/dist-packages/mmedit/datasets/pipelines/loading.py", line 8, in <module>
    from mmedit.core.mask import (bbox2mask, brush_stroke_mask, get_irregular_mask,
  File "/usr/local/lib/python3.8/dist-packages/mmedit/core/__init__.py", line 2, in <module>
    from .evaluation import (DistEvalIterHook, EvalIterHook, L1Evaluation, mse,
  File "/usr/local/lib/python3.8/dist-packages/mmedit/core/evaluation/__init__.py", line 3, in <module>
    from .metrics import (L1Evaluation, connectivity, gradient_error, mse, niqe,
  File "/usr/local/lib/python3.8/dist-packages/mmedit/core/evaluation/metrics.py", line 7, in <module>
    from scipy.ndimage import convolve
ModuleNotFoundError: No module named 'scipy'

pipe:: Invalid data found when processing input
root@5c2d1ace25dd:/workspace/tensorrt#

The pip install worked for that instance but the error came up the next time as well.
I ran this sequence before:

docker run --privileged --gpus all -it --rm -v //c/Users/efmcp/Documents/VSGAN/VSGAN-tensorrt-docker-main:/workspace/tensorrt vsgan_tensorrt:latest

cd tensorrt

vspipe -c y4m inference.py - | ffmpeg -i pipe: -c:v ffv1 -level 3 -threads 16 -slices 16 output.mkv

This is the modified inference.py that I used:
[inference.txt](https://github.com/styler00dollar/VSGAN-tensorrt-docker/files/8644653/inference.txt)

**Comment by terminatedkhla** [comment]
Also when I run the "pip install skipy" I get this message and an unplayable 1kb output file

root@5c2d1ace25dd:/workspace/tensorrt# vspipe -c y4m inference.py - | ffmpeg -i pipe: -c:v ffv1 -level 3 -threads 16 -slices 16 output.mkv
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Information: Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
Information: Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
Error: Failed to retrieve frame 0 with error: CUDA out of memory. Tried to allocate 102.00 MiB (GPU 0; 6.00 GiB total capacity; 5.12 GiB already allocated; 0 bytes free; 5.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output 4 frames in 2.89 seconds (1.38 fps)
Input #0, yuv4mpegpipe, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p(progressive), 3840x2160, 59.94 fps, 59.94 tbr, 59.94 tbn, 59.94 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> ffv1 (native))
Output #0, matroska, to 'output.mkv':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), yuv420p, 3840x2160, q=2-31, 200 kb/s, 59.94 fps, 1k tbn, 59.94 tbc
    Metadata:
      encoder         : Lavc58.54.100 ffv1
frame=    0 fps=0.0 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by styler00dollar** [comment]
At first glance it seems like I just need to add scipy to my dockerfile since it got added as a dependency. 

It actually worked afterwards, but you didn't have enough vram. It says "CUDA out of memory". Keep in mind that video super resolution models need a lot of vram compared to an image model like esrgan or compact. I would suggest using a lightweight model with that gpu, or lower the resolution. It is a hardware limit at that point. I can't open your inference.txt for some reason in my github app, so it's just general advise.

Also, you can format by using tripple quotation marks instead of simply pasting text, looks a lot cleaner.       

I will include scipy in my repo later.

**Comment by terminatedkhla** [comment]
Thank you so much for the support! This has been a rly cool program. I thought that this was more than enough vram, but I guess I was wrong. I use an RTX 2060 so It's less capable.
![image](https://user-images.githubusercontent.com/105093061/167253175-4a866768-8294-42cf-a7b6-96f393870010.png)

**Comment by styler00dollar** [comment]
On higher resolutions the vram that is needed can be quite high in some cases. Well the vram usage also depends on the input resolution, backend and what model is being used. In the context of deep learning, 6gb vram isnt even that much. 

I was finally able to look at your file. I had the idea to open that file url via browser. Like I mentioned in a prior github issue, cugan needs a lot vram. With 8gb vram you cant even process 1080p from what I heard. While I added that I was using Colab with 16gb vram and I was able to process 1080p. So that you can roughly guess how much vram it needs. With 6gb you probably can do 480p as input with cugan. It needs more than esrgan and compact in comparison.

**Comment by styler00dollar** [comment]
Should be fixed now.
