### ISSUE TITLE
Can ESRGAN still be utilized?

### ISSUE THREAD

**Issue by bpoxy** [styler00dollar/VSGAN-tensorrt-docker#71]
I've been using this project to run ESRGAN models for sometime now. However, I just pulled latest and noticed that ESRGAN support was removed several months back (05e9a8d). Is it still possible to run ESRGAN with some alternative method? Thanks.

**Comment by styler00dollar** [comment]
Yes, [follow the readme](https://github.com/styler00dollar/VSGAN-tensorrt-docker?tab=readme-ov-file#vs-mlrt). Export onnx with `torch.onnx.export` or chaiNNer and build engine like readme says. That way is way faster than the old python code I had.

**Comment by bpoxy** [comment]
Sorry, I got a bit mixed up as it has been a while since I looked at this project. I'm already converting the `pth` model to an `engine` to take advantage of the `trt` performance increase. However, I'm [utilizing the `ESRGAN` class to load the `pth` model](https://github.com/bpoxy/VSGAN-tensorrt-docker/blob/9e9035ec16aed15db0d5a9051b2ad53528c8be5e/models/build_engines.py#L32), which I pass to `torch.onnx.export`. How do I do this without `ESRGAN`? Thanks.

**Comment by styler00dollar** [comment]
Seems like you made a script to export onnx yourself, but I don't understand the question. After you have the onnx files you build engines. You need to have the python code to export onnx.

**Comment by bpoxy** [comment]
I am [calling `trtexec`](https://github.com/bpoxy/VSGAN-tensorrt-docker/blob/9e9035ec16aed15db0d5a9051b2ad53528c8be5e/models/build_engines.py#L15) after I generate the `onnx`. I'm just not sure how to go about generating the `onnx` with the latest codebase, since I was utilizing the `ESRGAN` previously. In other words, what should I pass as first argument to `torch.onnx.export` for an ESRGAN `pth` model now?

**Comment by styler00dollar** [comment]
Since I deleted esrgan from my code, you would need to add `esrgan.py` back if you want to keep using this export file. I usually just quickly copy architecture files from other sources when I export onnx.

**Comment by bpoxy** [comment]
Okay, I'll give that a shot. Thank you for all of your responses!
