### ISSUE TITLE
Consider (re)including `vapoursynth-mvtools` in the Docker image.

### ISSUE THREAD

**Issue by bpoxy** [styler00dollar/VSGAN-tensorrt-docker#72]
This library has some useful tools, in particular I was using `Degrain3`. Any reason you chose to remove this?
I tried installing it myself but ran into some issues.

**Comment by styler00dollar** [comment]
I had problems with mvtools. It broke at some point and was unusable. I remember code errors and visual artefacts. [Nobody wants to maintain it either.](
https://github.com/dubhater/vapoursynth-mvtools/issues/68) I won't add it back and I would recommend to look for alternatives. I removed mvtools from my code.

**Comment by bpoxy** [comment]
Ah, I see. Thanks for explanation.

**Comment by styler00dollar** [comment]
It seemingly got fixed afterwards, so I added it back since it was a dependency for another plugin.
