### ISSUE TITLE
Docker image styler00dollar/vsgan_tensorrt:trt9.3 missing modified bestsource for ddfi

### ISSUE THREAD

**Issue by Sg4Dylan** [styler00dollar/VSGAN-tensorrt-docker#80]
Docker image styler00dollar/vsgan_tensorrt:trt9.3 does not contain the fix shown below https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/bfdb96a329682af19d093ecb990f67e823ea2e89/Dockerfile#L354

---
I recompiled the trt9.3 corresponding Dockerfile to get the corrected `bestsource.so` , hopefully that helps anyone who needs it.

[bestsource.so.zip](https://github.com/user-attachments/files/17082645/bestsource.so.zip)

**Comment by styler00dollar** [comment]
Since there is no issue to solve I will close this, but thanks anyway. I don't really want to maintain old docker versions.
