### ISSUE TITLE
Error: Illegal instruction (core dumped) when running inference script

### ISSUE THREAD

**Issue by LongNTKR** [styler00dollar/VSGAN-tensorrt-docker#81]
### Environments:
- OS: Ubuntu 22.04.5 LTS
- Driver Version: 555.58.02
- CUDA Version: 12.5
- GPU: NVIDIA GeForce RTX 4090
- Docker version 27.3.1, build ce12230
- nvidia-container-toolkit: 1.16.1
- Image: styler00dollar/vsgan_tensorrt:latest (09/21/2024)
- Commit: [13f1210](https://github.com/styler00dollar/VSGAN-tensorrt-docker/commit/13f1210df76d33c120ceb04f67335b3eff760341)

### Code:
```python
import warnings
warnings.filterwarnings("ignore")
import sys
sys.path.append("/workspace/tensorrt/")
from inference_config import inference_clip
video_path = "/workspace/tensorrt/static_shot.mp4" # or /root/VSGAN-tensorrt-docker/static_shot.mp4
clip = inference_clip(video_path)
clip.set_output()
```

### Log:
vspipe -c y4m inference.py - | ffmpeg -i pipe: example.mkv
ffmpeg version N-117025-g6229e4ac42 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.1 (GCC) 20240910
  configuration: --extra-cflags='-march=native -fopenmp -lcrypto -lz -ldl -static-libgcc -I/opt/cuda/include' --extra-cxxflags='-march=native -fopenmp -lcrypto -lz -ldl -static-libgcc' --extra-ldflags='-L/usr/local/lib/xeve -fopenmp -lcrypto -lz -ldl -static-libgcc -L/opt/cuda/lib64' --extra-libs='-lstdc++ -lcrypto -lz -ldl -static-libgcc' --pkg-config-flags=--static --toolchain=hardened --disable-debug --disable-shared --disable-ffplay --enable-static --enable-gpl --enable-gray --enable-nonfree --enable-openssl --enable-iconv --enable-libxml2 --enable-libmp3lame --enable-libfdk-aac --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvpx --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libaom --enable-libvidstab --enable-libkvazaar --enable-libfreetype --enable-fontconfig --enable-libfribidi --enable-libass --enable-libsoxr --enable-libopenjpeg --enable-libdav1d --enable-librav1e --enable-libsrt --enable-libsvtav1 --enable-libdavs2 --enable-libvmaf --enable-libxeve --enable-vapoursynth --enable-libopenh264 --enable-optimizations --enable-nvdec --enable-nvenc --enable-cuvid --enable-cuda --enable-pthreads --enable-runtime-cpudetect --enable-lto
  libavutil      59. 36.100 / 59. 36.100
  libavcodec     61. 13.100 / 61. 13.100
  libavformat    61.  5.101 / 61.  5.101
  libavdevice    61.  2.101 / 61.  2.101
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Illegal instruction (core dumped)

### Additional Information:
- I am using the latest Docker image as specified above.
- The error occurs when I try to run the inference script through VapourSynth and pipe it to FFmpeg.
- I have followed these instructions:
  - docker pull styler00dollar/vsgan_tensorrt:latest
  - git clone https://github.com/styler00dollar/VSGAN-tensorrt-docker.git
  - cd VSGAN-tensorrt-docker
  - sudo docker run --privileged --gpus all -it --rm -v /root/VSGAN-tensorrt-docker:/workspace/tensorrt styler00dollar/vsgan_tensorrt:latest
  - vspipe -c y4m inference.py - | ffmpeg -i pipe: example.mkv
 
### Questions:

1. How can I diagnose or resolve this?
2. Does VapourSynth require any additional installation or configuration within the Docker container? 
   If so, are there specific steps or dependencies that need to be verified?
3. I'm also interested in using Real-ESRGAN with this setup. Are there any specific instructions or considerations for integrating Real-ESRGAN into this workflow? 

### Thank you for your time and assistance!

**Comment by styler00dollar** [comment]
> How can I diagnose or resolve this?
> Does VapourSynth require any additional installation or configuration within the Docker container?
If so, are there specific steps or dependencies that need to be verified?

You didn't read the readme. You use the avx docker on a non-avx cpu. Use the non-avx docker.

> I'm also interested in using Real-ESRGAN with this setup. Are there any specific instructions or considerations for integrating Real-ESRGAN into this workflow?

Use `core.trt` like the readme shows or look at [other mlrt examples](https://github.com/styler00dollar/VSGAN-tensorrt-docker/tree/main/custom_scripts).

**Comment by LongNTKR** [comment]
Thank you very much for your prompt response. I’ve successfully completed and run the code. Now, I would like to increase the speed further. I adjusted the **num_streams** from 1 to 2, and it improved the performance. However, increasing it to 3 or 4 did not show any noticeable difference. I also tried increasing the **num_threads**, but there was no change either. It seems like I’m hitting the limitations of my hardware.

I also attempted to use **inference_clip_batch**, but I encountered the following error:

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/workspace/tensorrt/inputs/v17.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf58.29.100
>   Duration: 00:00:05.21, start: 0.000000, bitrate: 6114 kb/s
>   Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x768, 6087 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
>       Metadata:
>         handler_name    : VideoHandler
>         vendor_id       : [0][0][0][0]
> Script evaluation failed:
> Python exception: operator(): expects 3 input planes
> 
> Traceback (most recent call last):
>   File "src/cython/vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluate
>   File "src/cython/vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluate
>   File "inference_batch.py", line 6, in <module>
>     clip = inference_clip_batch(
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/workspace/tensorrt/inference_config.py", line 24, in inference_clip_batch
>     clip = core.trt.Model(
>            ^^^^^^^^^^^^^^^
>   File "src/cython/vapoursynth.pyx", line 3123, in vapoursynth.Function.__call__
> vapoursynth.Error: operator(): expects 3 input planes

I’d like to mention the code I used, which caused the error:
```python
def inference_clip_batch(video_path="", clip=None):
    if clip is None:
        clip = core.bs.VideoSource(source=video_path)
        
    clip = vs.core.resize.Bicubic(clip, height=768, width=1280, format=vs.RGBS, matrix_in_s="709")

    stream0 = core.std.SelectEvery(clip, cycle=2, offsets=0)
    stream1 = core.std.SelectEvery(clip, cycle=2, offsets=1)
    
    #This code checks if the number of frames is odd, and if so, it appends the last frame to stream1 to ensure both stream0 and 
    #stream1 have the same number of frames for further processing.
    if clip.num_frames % 2 != 0:
        last_frame = core.std.Trim(clip, clip.num_frames - 1, clip.num_frames - 1)
        stream1 = core.std.Splice([stream1, last_frame])

    prop = "test"
    clip = core.trt.Model(
        [stream0, stream1],
        engine_path="/workspace/tensorrt/engine/RealESRGAN_x4plus_1080_1920.engine",
        num_streams=4,
        flexible_output_prop="test",
    )
    out0 = core.std.ShufflePlanes(
        [clip["clip"].std.PropToClip(prop=f"{prop}{i}") for i in range(3)],
        [0, 0, 0],
        vs.RGB,
    )
    out1 = core.std.ShufflePlanes(
        [clip["clip"].std.PropToClip(prop=f"{prop}{i}") for i in range(3, 6)],
        [0, 0, 0],
        vs.RGB,
    )

    clip = core.std.Interleave([out0, out1])

    clip = vs.core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s="709")
    return clip
```
Could you help me understand what this error means?

**Comment by styler00dollar** [comment]
Don't ask different questions in one issue, but to answer, at a certain point increasing `num_streams` won't help if your gpu is fully utilized. Too many can even harm performance. Batched inference requires a special onnx/engine, use my other examples as reference with a 3 channel model.

https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/6a55f286a893485e816e3222ec129343233ce75a/custom_scripts/inference_batched_upscale.py#L13-L14
